CREATE TYPE star_rating AS ENUM
('1', '2', '3', '4', '5')

CREATE TABLE bookmarks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT,
    rating star_rating NOT NULL DEFAULT 1
);

/*
//const bookmarks = [
// {
//   id: 0,
//   title: 'Google',
//   url: 'http://www.google.com',
//   rating: '3',
//   desc: 'Internet-related services and products.'
// },
*/